[debug] [2020-04-12T15:19:30.576Z] ----------------------------------------------------------------------
[debug] [2020-04-12T15:19:30.579Z] Command:       /usr/local/bin/node /usr/local/bin/firebase init
[debug] [2020-04-12T15:19:30.579Z] CLI Version:   8.0.2
[debug] [2020-04-12T15:19:30.580Z] Platform:      darwin
[debug] [2020-04-12T15:19:30.580Z] Node Version:  v12.14.0
[debug] [2020-04-12T15:19:30.581Z] Time:          Sun Apr 12 2020 17:19:30 GMT+0200 (Central European Summer Time)
[debug] [2020-04-12T15:19:30.581Z] ----------------------------------------------------------------------
[debug] [2020-04-12T15:19:30.581Z] 
[debug] [2020-04-12T15:19:30.608Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-12T15:19:30.667Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
